# head-branch -> label based on PR branch name
# changed-files -> label based on files changed in the PR

feature:
  - head-branch:
      - "feature/*"

fix:
  - head-branch:
      - "fix/*"

chore:
  - head-branch:
      - "chore/*"

docs:
  - head-branch:
      - "docs/*"
  - changed-files:
      - any-glob-to-any-file: "docs/**"

refactor:
  - head-branch:
      - "refactor/*"

test:
  - head-branch:
      - "test/*"
  - changed-files:
      - any-glob-to-any-file: "backend/Cayeshni.Tests/**"

hotfix:
  - head-branch:
      - "hotfix/*"

frontend:
  - changed-files:
      - any-glob-to-any-file: "frontend/**"

backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**"