# head-branch: -> label based on PR branch name (regex)
# folder-name/** -> label based on changed files in the PR

feature:
  - head-branch: ['^feature/']

fix:
  - head-branch: ['^fix/']

chore:
  - head-branch: ['^chore/']

docs:
  - head-branch: ['^docs/']
  - "docs/**"

refactor:
  - head-branch: ['^refactor/']

test:
  - "test/**"
  - "backend/Cayeshni.Tests/**"
  # todo: add frontend test folder later when we have frontend tests

hotfix:
  - head-branch: ['^hotfix/']

frontend:
  - "frontend/**"

backend:
  - "backend/**"