# branch-name/* -> label based on branch name
# folder-name/** -> label based on changed files in the PR

feature:
  - "feature/*"

fix:
  - "fix/*"

chore:
  - "chore/*"

docs:
  - "docs/*"
  - "docs/**"

refactor:
  - "refactor/*"

test:
  - "test/*"
  - "test/**"
  - "backend/Cayeshni.Tests/**"
  # todo: add frontend test folder later when we have frontend tests

hotfix:
  - "hotfix/*"

frontend:
  - "frontend/**"

backend:
  - "backend/**"