using System.ComponentModel.DataAnnotations;
using Cayeshni.Application.Common.Interfaces;
using Cayeshni.Domain.Enums;
using Cayeshni.Infrastructure.Persistence.Options;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;

public class CloudinaryFileStorageService : IFileStorageService
{
    private readonly Cloudinary _cloudinary;
    private readonly FileStorageOptions _options;

    public CloudinaryFileStorageService(IConfiguration config, IOptions<FileStorageOptions> options)
    {
        _options = options.Value;

        var account = new Account(
            config["Cloudinary:CloudName"],
            config["Cloudinary:ApiKey"],
            config["Cloudinary:ApiSecret"]
        );
        _cloudinary = new Cloudinary(account) { Api = { Secure = true } };
    }

    public async Task<string> SaveAsync(Stream fileStream, string fileName, string contentType, FileFolder folder)
    {
        if (fileStream.Length > _options.MaxUploadSizeMb * 1024 * 1024)
            throw new ValidationException($"File too large. Max {_options.MaxUploadSizeMb}MB allowed.");

        var extension = Path.GetExtension(fileName).ToLowerInvariant();
        if (!_options.AllowedExtensions.Contains(extension))
            throw new ValidationException($"Invalid file type. Allowed: {string.Join(", ", _options.AllowedExtensions)}");

        var folderName = folder.ToString().ToLowerInvariant();

        var uploadParams = new ImageUploadParams
        {
            File = new FileDescription(fileName, fileStream),
            Folder = $"cayeshni/{folderName}",
            UseFilename = false, // we generate our own unique name, so ignore original filename
            UniqueFilename = true, // ensures a unique name is generated by Cloudinary
            Overwrite = false
        };

        var result = await _cloudinary.UploadAsync(uploadParams);

        if (result.Error != null)
            throw new InvalidOperationException($"Cloudinary upload failed: {result.Error.Message}");

        // returns full HTTPS URL - this is what gets stored in DB
        return result.SecureUrl.ToString();
    }

    public async Task DeleteAsync(string storedPath)
    {
        if (string.IsNullOrWhiteSpace(storedPath))
            return;

        var publicId = ExtractPublicId(storedPath);
        if (publicId == null) return;

        await _cloudinary.DestroyAsync(new DeletionParams(publicId));
    }

    public string GetUrl(string? storedPath, string? defaultName = "avatar")
    {
        if (string.IsNullOrWhiteSpace(storedPath))
            return $"{_options.BaseUrl.TrimEnd('/')}/defaults/{defaultName}.webp";

        // storedPath is already a full Cloudinary URL
        return storedPath;
    }

    public string GetBaseUrl() => _options.BaseUrl.TrimEnd('/');

    private static string? ExtractPublicId(string cloudinaryUrl)
    {
        // url format: https://res.cloudinary.com/{cloud_name}/image/upload/v1234567/{folder}/{public_id}.jpg
        // e.g. https://res.cloudinary.com/mycloud/image/upload/v1234567/cayeshni/profiles/abc.webp
        var uploadSegment = "/upload/";
        var idx = cloudinaryUrl.IndexOf(uploadSegment, StringComparison.Ordinal);
        if (idx < 0) return null;

        var afterUpload = cloudinaryUrl[(idx + uploadSegment.Length)..]; // e.g. "v1234567/cayeshni/profiles/abc.webp"

        // strip version segment (v1234567/)
        if (afterUpload.StartsWith('v') && afterUpload.Contains('/'))
        {
            var slashIdx = afterUpload.IndexOf('/');
            afterUpload = afterUpload[(slashIdx + 1)..]; // e.g. "cayeshni/profiles/abc.webp"
        }

        // strip extension e.g. ".webp"
        var dotIdx = afterUpload.LastIndexOf('.');
        return dotIdx >= 0 ? afterUpload[..dotIdx] : afterUpload; // returns "cayeshni/profiles/abc"
    }
}