name: PR Validation (develop)

on:
  pull_request:
    branches: [develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title (Conventional Commits)
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate branch name
        # I added main for syncing with develop if I hotfix to main, I can sync back to develop
        run: |
          BRANCH="${{ github.head_ref }}"

          if [[ ! "$BRANCH" =~ ^(feature/|fix/|chore/|docs/|refactor/|test/|hotfix/) && ! "$BRANCH" =~ ^main ]]; then
            echo "❌ Invalid branch for develop: $BRANCH"
            echo "Allowed prefixes: feature/, fix/, chore/, docs/, refactor/, test/, hotfix/ or main"
            exit 1
          fi